[package]
name = "verusc"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.2.0"
regex = "1.11.1"
serde_json = "1.0.134"
shell-words = "1.1.0"
toml = "0.8.19"
