[package]
name = "acc-extension"
version = "0.1.0"
authors = ["Michael Lum <mlum@umd.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
openssl = { version = "0.10.33", features = ["vendored"] }
