[package]
name = "vest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
builtin_macros = { path = "../verus/source/builtin_macros" }
builtin = { path = "../verus/source/builtin" }
vstd = { path = "../verus/source/vstd" }

[dev-dependencies]

[package.metadata.verus.ide]
extra_args = "--crate-type=lib --expand-errors --test"
