open Pkcs1

let string_of_char c = String.make 1 c

(* Converts a string to a list of chars *)
let explode str =
  let rec explode_inner cur_index chars =
    if cur_index < String.length str then
      let new_char = str.[cur_index] in
      explode_inner (cur_index + 1) (chars @ [new_char])
    else chars in
  explode_inner 0 []

(* Converts a list of chars to a string *)
let rec implode chars =
  match chars with
  [] -> ""
  | h::t ->  string_of_char h ^ (implode t)


let rec byte_list_of_hex_string str  = 
  match explode str with
  | [] -> []
  | _::[] -> []
  | b1::b2::t -> match Char.code(b1), Char.code(b2) with
                 | 48,48  -> X00 :: byte_list_of_hex_string (implode t) 
                 | 48,49  -> X01 :: byte_list_of_hex_string (implode t) 
                 | 48,50  -> X02 :: byte_list_of_hex_string (implode t) 
                 | 48,51  -> X03 :: byte_list_of_hex_string (implode t) 
                 | 48,52  -> X04 :: byte_list_of_hex_string (implode t) 
                 | 48,53  -> X05 :: byte_list_of_hex_string (implode t) 
                 | 48,54  -> X06 :: byte_list_of_hex_string (implode t) 
                 | 48,55  -> X07 :: byte_list_of_hex_string (implode t) 
                 | 48,56  -> X08 :: byte_list_of_hex_string (implode t) 
                 | 48,57  -> X09 :: byte_list_of_hex_string (implode t) 
                 | 48,97  -> X0a :: byte_list_of_hex_string (implode t) 
                 | 48,98  -> X0b :: byte_list_of_hex_string (implode t) 
                 | 48,99  -> X0c :: byte_list_of_hex_string (implode t) 
                 | 48,100 -> X0d :: byte_list_of_hex_string (implode t) 
                 | 48,101 -> X0e :: byte_list_of_hex_string (implode t) 
                 | 48,102 -> X0f :: byte_list_of_hex_string (implode t) 
                 | 49,48  -> X10 :: byte_list_of_hex_string (implode t) 
                 | 49,49  -> X11 :: byte_list_of_hex_string (implode t) 
                 | 49,50  -> X12 :: byte_list_of_hex_string (implode t) 
                 | 49,51  -> X13 :: byte_list_of_hex_string (implode t) 
                 | 49,52  -> X14 :: byte_list_of_hex_string (implode t) 
                 | 49,53  -> X15 :: byte_list_of_hex_string (implode t) 
                 | 49,54  -> X16 :: byte_list_of_hex_string (implode t) 
                 | 49,55  -> X17 :: byte_list_of_hex_string (implode t) 
                 | 49,56  -> X18 :: byte_list_of_hex_string (implode t) 
                 | 49,57  -> X19 :: byte_list_of_hex_string (implode t) 
                 | 49,97  -> X1a :: byte_list_of_hex_string (implode t) 
                 | 49,98  -> X1b :: byte_list_of_hex_string (implode t) 
                 | 49,99  -> X1c :: byte_list_of_hex_string (implode t) 
                 | 49,100 -> X1d :: byte_list_of_hex_string (implode t) 
                 | 49,101 -> X1e :: byte_list_of_hex_string (implode t) 
                 | 49,102 -> X1f :: byte_list_of_hex_string (implode t) 
                 | 50,48  -> X20 :: byte_list_of_hex_string (implode t) 
                 | 50,49  -> X21 :: byte_list_of_hex_string (implode t) 
                 | 50,50  -> X22 :: byte_list_of_hex_string (implode t) 
                 | 50,51  -> X23 :: byte_list_of_hex_string (implode t) 
                 | 50,52  -> X24 :: byte_list_of_hex_string (implode t) 
                 | 50,53  -> X25 :: byte_list_of_hex_string (implode t) 
                 | 50,54  -> X26 :: byte_list_of_hex_string (implode t) 
                 | 50,55  -> X27 :: byte_list_of_hex_string (implode t) 
                 | 50,56  -> X28 :: byte_list_of_hex_string (implode t) 
                 | 50,57  -> X29 :: byte_list_of_hex_string (implode t) 
                 | 50,97  -> X2a :: byte_list_of_hex_string (implode t) 
                 | 50,98  -> X2b :: byte_list_of_hex_string (implode t) 
                 | 50,99  -> X2c :: byte_list_of_hex_string (implode t) 
                 | 50,100 -> X2d :: byte_list_of_hex_string (implode t) 
                 | 50,101 -> X2e :: byte_list_of_hex_string (implode t) 
                 | 50,102 -> X2f :: byte_list_of_hex_string (implode t) 
                 | 51,48  -> X30 :: byte_list_of_hex_string (implode t) 
                 | 51,49  -> X31 :: byte_list_of_hex_string (implode t) 
                 | 51,50  -> X32 :: byte_list_of_hex_string (implode t) 
                 | 51,51  -> X33 :: byte_list_of_hex_string (implode t) 
                 | 51,52  -> X34 :: byte_list_of_hex_string (implode t) 
                 | 51,53  -> X35 :: byte_list_of_hex_string (implode t) 
                 | 51,54  -> X36 :: byte_list_of_hex_string (implode t) 
                 | 51,55  -> X37 :: byte_list_of_hex_string (implode t) 
                 | 51,56  -> X38 :: byte_list_of_hex_string (implode t) 
                 | 51,57  -> X39 :: byte_list_of_hex_string (implode t) 
                 | 51,97  -> X3a :: byte_list_of_hex_string (implode t) 
                 | 51,98  -> X3b :: byte_list_of_hex_string (implode t) 
                 | 51,99  -> X3c :: byte_list_of_hex_string (implode t) 
                 | 51,100 -> X3d :: byte_list_of_hex_string (implode t) 
                 | 51,101 -> X3e :: byte_list_of_hex_string (implode t) 
                 | 51,102 -> X3f :: byte_list_of_hex_string (implode t) 
                 | 52,48  -> X40 :: byte_list_of_hex_string (implode t) 
                 | 52,49  -> X41 :: byte_list_of_hex_string (implode t) 
                 | 52,50  -> X42 :: byte_list_of_hex_string (implode t) 
                 | 52,51  -> X43 :: byte_list_of_hex_string (implode t) 
                 | 52,52  -> X44 :: byte_list_of_hex_string (implode t) 
                 | 52,53  -> X45 :: byte_list_of_hex_string (implode t) 
                 | 52,54  -> X46 :: byte_list_of_hex_string (implode t) 
                 | 52,55  -> X47 :: byte_list_of_hex_string (implode t) 
                 | 52,56  -> X48 :: byte_list_of_hex_string (implode t) 
                 | 52,57  -> X49 :: byte_list_of_hex_string (implode t) 
                 | 52,97  -> X4a :: byte_list_of_hex_string (implode t) 
                 | 52,98  -> X4b :: byte_list_of_hex_string (implode t) 
                 | 52,99  -> X4c :: byte_list_of_hex_string (implode t) 
                 | 52,100 -> X4d :: byte_list_of_hex_string (implode t) 
                 | 52,101 -> X4e :: byte_list_of_hex_string (implode t) 
                 | 52,102 -> X4f :: byte_list_of_hex_string (implode t) 
                 | 53,48  -> X50 :: byte_list_of_hex_string (implode t) 
                 | 53,49  -> X51 :: byte_list_of_hex_string (implode t) 
                 | 53,50  -> X52 :: byte_list_of_hex_string (implode t) 
                 | 53,51  -> X53 :: byte_list_of_hex_string (implode t) 
                 | 53,52  -> X54 :: byte_list_of_hex_string (implode t) 
                 | 53,53  -> X55 :: byte_list_of_hex_string (implode t) 
                 | 53,54  -> X56 :: byte_list_of_hex_string (implode t) 
                 | 53,55  -> X57 :: byte_list_of_hex_string (implode t) 
                 | 53,56  -> X58 :: byte_list_of_hex_string (implode t) 
                 | 53,57  -> X59 :: byte_list_of_hex_string (implode t) 
                 | 53,97  -> X5a :: byte_list_of_hex_string (implode t) 
                 | 53,98  -> X5b :: byte_list_of_hex_string (implode t) 
                 | 53,99  -> X5c :: byte_list_of_hex_string (implode t) 
                 | 53,100 -> X5d :: byte_list_of_hex_string (implode t) 
                 | 53,101 -> X5e :: byte_list_of_hex_string (implode t) 
                 | 53,102 -> X5f :: byte_list_of_hex_string (implode t) 
                 | 54,48  -> X60 :: byte_list_of_hex_string (implode t) 
                 | 54,49  -> X61 :: byte_list_of_hex_string (implode t) 
                 | 54,50  -> X62 :: byte_list_of_hex_string (implode t) 
                 | 54,51  -> X63 :: byte_list_of_hex_string (implode t) 
                 | 54,52  -> X64 :: byte_list_of_hex_string (implode t) 
                 | 54,53  -> X65 :: byte_list_of_hex_string (implode t) 
                 | 54,54  -> X66 :: byte_list_of_hex_string (implode t) 
                 | 54,55  -> X67 :: byte_list_of_hex_string (implode t) 
                 | 54,56  -> X68 :: byte_list_of_hex_string (implode t) 
                 | 54,57  -> X69 :: byte_list_of_hex_string (implode t) 
                 | 54,97  -> X6a :: byte_list_of_hex_string (implode t) 
                 | 54,98  -> X6b :: byte_list_of_hex_string (implode t) 
                 | 54,99  -> X6c :: byte_list_of_hex_string (implode t) 
                 | 54,100 -> X6d :: byte_list_of_hex_string (implode t) 
                 | 54,101 -> X6e :: byte_list_of_hex_string (implode t) 
                 | 54,102 -> X6f :: byte_list_of_hex_string (implode t) 
                 | 55,48  -> X70 :: byte_list_of_hex_string (implode t) 
                 | 55,49  -> X71 :: byte_list_of_hex_string (implode t) 
                 | 55,50  -> X72 :: byte_list_of_hex_string (implode t) 
                 | 55,51  -> X73 :: byte_list_of_hex_string (implode t) 
                 | 55,52  -> X74 :: byte_list_of_hex_string (implode t) 
                 | 55,53  -> X75 :: byte_list_of_hex_string (implode t) 
                 | 55,54  -> X76 :: byte_list_of_hex_string (implode t) 
                 | 55,55  -> X77 :: byte_list_of_hex_string (implode t) 
                 | 55,56  -> X78 :: byte_list_of_hex_string (implode t) 
                 | 55,57  -> X79 :: byte_list_of_hex_string (implode t) 
                 | 55,97  -> X7a :: byte_list_of_hex_string (implode t) 
                 | 55,98  -> X7b :: byte_list_of_hex_string (implode t) 
                 | 55,99  -> X7c :: byte_list_of_hex_string (implode t) 
                 | 55,100 -> X7d :: byte_list_of_hex_string (implode t) 
                 | 55,101 -> X7e :: byte_list_of_hex_string (implode t) 
                 | 55,102 -> X7f :: byte_list_of_hex_string (implode t) 
                 | 56,48  -> X80 :: byte_list_of_hex_string (implode t) 
                 | 56,49  -> X81 :: byte_list_of_hex_string (implode t) 
                 | 56,50  -> X82 :: byte_list_of_hex_string (implode t) 
                 | 56,51  -> X83 :: byte_list_of_hex_string (implode t) 
                 | 56,52  -> X84 :: byte_list_of_hex_string (implode t) 
                 | 56,53  -> X85 :: byte_list_of_hex_string (implode t) 
                 | 56,54  -> X86 :: byte_list_of_hex_string (implode t) 
                 | 56,55  -> X87 :: byte_list_of_hex_string (implode t) 
                 | 56,56  -> X88 :: byte_list_of_hex_string (implode t) 
                 | 56,57  -> X89 :: byte_list_of_hex_string (implode t) 
                 | 56,97  -> X8a :: byte_list_of_hex_string (implode t) 
                 | 56,98  -> X8b :: byte_list_of_hex_string (implode t) 
                 | 56,99  -> X8c :: byte_list_of_hex_string (implode t) 
                 | 56,100 -> X8d :: byte_list_of_hex_string (implode t) 
                 | 56,101 -> X8e :: byte_list_of_hex_string (implode t) 
                 | 56,102 -> X8f :: byte_list_of_hex_string (implode t) 
                 | 57,48  -> X90 :: byte_list_of_hex_string (implode t) 
                 | 57,49  -> X91 :: byte_list_of_hex_string (implode t) 
                 | 57,50  -> X92 :: byte_list_of_hex_string (implode t) 
                 | 57,51  -> X93 :: byte_list_of_hex_string (implode t) 
                 | 57,52  -> X94 :: byte_list_of_hex_string (implode t) 
                 | 57,53  -> X95 :: byte_list_of_hex_string (implode t) 
                 | 57,54  -> X96 :: byte_list_of_hex_string (implode t) 
                 | 57,55  -> X97 :: byte_list_of_hex_string (implode t) 
                 | 57,56  -> X98 :: byte_list_of_hex_string (implode t) 
                 | 57,57  -> X99 :: byte_list_of_hex_string (implode t) 
                 | 57,97  -> X9a :: byte_list_of_hex_string (implode t) 
                 | 57,98  -> X9b :: byte_list_of_hex_string (implode t) 
                 | 57,99  -> X9c :: byte_list_of_hex_string (implode t) 
                 | 57,100 -> X9d :: byte_list_of_hex_string (implode t) 
                 | 57,101 -> X9e :: byte_list_of_hex_string (implode t) 
                 | 57,102 -> X9f :: byte_list_of_hex_string (implode t) 
                 | 97,48  -> Xa0 :: byte_list_of_hex_string (implode t) 
                 | 97,49  -> Xa1 :: byte_list_of_hex_string (implode t) 
                 | 97,50  -> Xa2 :: byte_list_of_hex_string (implode t) 
                 | 97,51  -> Xa3 :: byte_list_of_hex_string (implode t) 
                 | 97,52  -> Xa4 :: byte_list_of_hex_string (implode t) 
                 | 97,53  -> Xa5 :: byte_list_of_hex_string (implode t) 
                 | 97,54  -> Xa6 :: byte_list_of_hex_string (implode t) 
                 | 97,55  -> Xa7 :: byte_list_of_hex_string (implode t) 
                 | 97,56  -> Xa8 :: byte_list_of_hex_string (implode t) 
                 | 97,57  -> Xa9 :: byte_list_of_hex_string (implode t) 
                 | 97,97  -> Xaa :: byte_list_of_hex_string (implode t) 
                 | 97,98  -> Xab :: byte_list_of_hex_string (implode t) 
                 | 97,99  -> Xac :: byte_list_of_hex_string (implode t) 
                 | 97,100 -> Xad :: byte_list_of_hex_string (implode t) 
                 | 97,101 -> Xae :: byte_list_of_hex_string (implode t) 
                 | 97,102 -> Xaf :: byte_list_of_hex_string (implode t) 
                 | 98,48  -> Xb0 :: byte_list_of_hex_string (implode t) 
                 | 98,49  -> Xb1 :: byte_list_of_hex_string (implode t) 
                 | 98,50  -> Xb2 :: byte_list_of_hex_string (implode t) 
                 | 98,51  -> Xb3 :: byte_list_of_hex_string (implode t) 
                 | 98,52  -> Xb4 :: byte_list_of_hex_string (implode t) 
                 | 98,53  -> Xb5 :: byte_list_of_hex_string (implode t) 
                 | 98,54  -> Xb6 :: byte_list_of_hex_string (implode t) 
                 | 98,55  -> Xb7 :: byte_list_of_hex_string (implode t) 
                 | 98,56  -> Xb8 :: byte_list_of_hex_string (implode t) 
                 | 98,57  -> Xb9 :: byte_list_of_hex_string (implode t) 
                 | 98,97  -> Xba :: byte_list_of_hex_string (implode t) 
                 | 98,98  -> Xbb :: byte_list_of_hex_string (implode t) 
                 | 98,99  -> Xbc :: byte_list_of_hex_string (implode t) 
                 | 98,100 -> Xbd :: byte_list_of_hex_string (implode t) 
                 | 98,101 -> Xbe :: byte_list_of_hex_string (implode t) 
                 | 98,102 -> Xbf :: byte_list_of_hex_string (implode t) 
                 | 99,48  -> Xc0 :: byte_list_of_hex_string (implode t) 
                 | 99,49  -> Xc1 :: byte_list_of_hex_string (implode t) 
                 | 99,50  -> Xc2 :: byte_list_of_hex_string (implode t) 
                 | 99,51  -> Xc3 :: byte_list_of_hex_string (implode t) 
                 | 99,52  -> Xc4 :: byte_list_of_hex_string (implode t) 
                 | 99,53  -> Xc5 :: byte_list_of_hex_string (implode t) 
                 | 99,54  -> Xc6 :: byte_list_of_hex_string (implode t) 
                 | 99,55  -> Xc7 :: byte_list_of_hex_string (implode t) 
                 | 99,56  -> Xc8 :: byte_list_of_hex_string (implode t) 
                 | 99,57  -> Xc9 :: byte_list_of_hex_string (implode t) 
                 | 99,97  -> Xca :: byte_list_of_hex_string (implode t) 
                 | 99,98  -> Xcb :: byte_list_of_hex_string (implode t) 
                 | 99,99  -> Xcc :: byte_list_of_hex_string (implode t) 
                 | 99,100 -> Xcd :: byte_list_of_hex_string (implode t) 
                 | 99,101 -> Xce :: byte_list_of_hex_string (implode t) 
                 | 99,102 -> Xcf :: byte_list_of_hex_string (implode t) 
                 | 100,48 -> Xd0 :: byte_list_of_hex_string (implode t) 
                 | 100,49 -> Xd1 :: byte_list_of_hex_string (implode t) 
                 | 100,50 -> Xd2 :: byte_list_of_hex_string (implode t) 
                 | 100,51 -> Xd3 :: byte_list_of_hex_string (implode t) 
                 | 100,52 -> Xd4 :: byte_list_of_hex_string (implode t) 
                 | 100,53 -> Xd5 :: byte_list_of_hex_string (implode t) 
                 | 100,54 -> Xd6 :: byte_list_of_hex_string (implode t) 
                 | 100,55 -> Xd7 :: byte_list_of_hex_string (implode t) 
                 | 100,56 -> Xd8 :: byte_list_of_hex_string (implode t) 
                 | 100,57 -> Xd9 :: byte_list_of_hex_string (implode t) 
                 | 100,97 -> Xda :: byte_list_of_hex_string (implode t) 
                 | 100,98 -> Xdb :: byte_list_of_hex_string (implode t) 
                 | 100,99 -> Xdc :: byte_list_of_hex_string (implode t) 
                 | 100,100 -> Xdd :: byte_list_of_hex_string (implode t) 
                 | 100,101 -> Xde :: byte_list_of_hex_string (implode t) 
                 | 100,102 -> Xdf :: byte_list_of_hex_string (implode t) 
                 | 101,48 -> Xe0 :: byte_list_of_hex_string (implode t) 
                 | 101,49 -> Xe1 :: byte_list_of_hex_string (implode t) 
                 | 101,50 -> Xe2 :: byte_list_of_hex_string (implode t) 
                 | 101,51 -> Xe3 :: byte_list_of_hex_string (implode t) 
                 | 101,52 -> Xe4 :: byte_list_of_hex_string (implode t) 
                 | 101,53 -> Xe5 :: byte_list_of_hex_string (implode t) 
                 | 101,54 -> Xe6 :: byte_list_of_hex_string (implode t) 
                 | 101,55 -> Xe7 :: byte_list_of_hex_string (implode t) 
                 | 101,56 -> Xe8 :: byte_list_of_hex_string (implode t) 
                 | 101,57 -> Xe9 :: byte_list_of_hex_string (implode t) 
                 | 101,97 -> Xea :: byte_list_of_hex_string (implode t) 
                 | 101,98 -> Xeb :: byte_list_of_hex_string (implode t) 
                 | 101,99 -> Xec :: byte_list_of_hex_string (implode t) 
                 | 101,100 -> Xed :: byte_list_of_hex_string (implode t) 
                 | 101,101 -> Xee :: byte_list_of_hex_string (implode t) 
                 | 101,102 -> Xef :: byte_list_of_hex_string (implode t) 
                 | 102,48 -> Xf0 :: byte_list_of_hex_string (implode t) 
                 | 102,49 -> Xf1 :: byte_list_of_hex_string (implode t) 
                 | 102,50 -> Xf2 :: byte_list_of_hex_string (implode t) 
                 | 102,51 -> Xf3 :: byte_list_of_hex_string (implode t) 
                 | 102,52 -> Xf4 :: byte_list_of_hex_string (implode t) 
                 | 102,53 -> Xf5 :: byte_list_of_hex_string (implode t) 
                 | 102,54 -> Xf6 :: byte_list_of_hex_string (implode t) 
                 | 102,55 -> Xf7 :: byte_list_of_hex_string (implode t) 
                 | 102,56 -> Xf8 :: byte_list_of_hex_string (implode t) 
                 | 102,57 -> Xf9 :: byte_list_of_hex_string (implode t) 
                 | 102,97 -> Xfa :: byte_list_of_hex_string (implode t) 
                 | 102,98 -> Xfb :: byte_list_of_hex_string (implode t) 
                 | 102,99 -> Xfc :: byte_list_of_hex_string (implode t) 
                 | 102,100 -> Xfd :: byte_list_of_hex_string (implode t) 
                 | 102,101 -> Xfe :: byte_list_of_hex_string (implode t) 
                 | 102,102 -> Xff :: byte_list_of_hex_string (implode t) 
                 | _,_ -> [] 

let hash_id_of_int id =
  match int_of_string id with
  | 1   -> Some (Sha1)
  | 224 -> Some (Sha224)
  | 256 -> Some (Sha256)
  | 384 -> Some (Sha384)
  | 512 -> Some (Sha512)
  | _   -> None

let sanitize_hex_string str =
  if (String.length str) mod 2 != 0 then
    "0" ^ (String.lowercase_ascii str)
  else 
    String.lowercase_ascii str

let parse_command_line_args () =
  let num_args = (Array.length Sys.argv) - 1 in
  if num_args <> 4 then
    None
  else
    if (int_of_string Sys.argv.(2)) >= 0 then      
      match (hash_id_of_int Sys.argv.(4)) with
      | None    -> None
      | Some id -> Some ((byte_list_of_hex_string (sanitize_hex_string Sys.argv.(1))), (int_of_string Sys.argv.(2)), (byte_list_of_hex_string (sanitize_hex_string Sys.argv.(3))), id)
    else
      None

let main () =
  match parse_command_line_args () with
  | Some (buffer, public_modulus_length, hash_value, hash_alg) ->
    let result = signature_verification buffer public_modulus_length hash_value hash_alg in
    Format.eprintf "%B@." result 
  | None ->
    if (int_of_string Sys.argv.(2)) < 0 then
      Format.eprintf "false @."
    else            
      Format.eprintf
        "Usage: %s <input_buffer> <public_modulus> <hash_value> <hash_algorithm_name>@."
        Sys.argv.(0);
      exit 1

let () = main ()

